# Generated by Django 5.2 on 2025-05-22 20:38

import core.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактна інформація', 'verbose_name_plural': 'Контактна інформація'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['display_order'], 'verbose_name': 'Елемент галереї', 'verbose_name_plural': 'Елементи галереї'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункти меню'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order'], 'verbose_name': 'Сторінка', 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секція', 'verbose_name_plural': 'Секції'},
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='card',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon',
            field=models.ImageField(upload_to=core.models.icon_upload_to, verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='card',
            name='link_text',
            field=models.CharField(default='Дізнатись більше', max_length=255, verbose_name='Текст посилання'),
        ),
        migrations.AlterField(
            model_name='card',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.section', verbose_name='Секція'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store_name',
            field=models.CharField(default='Мій магазин', max_length=255, verbose_name='Назва магазину'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Робочий годинник'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to=core.models.gallery_upload_to, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page', verbose_name='Сторінка'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Батько'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Якщо вказано, використовуватиметься це посилання замість сторінки', max_length=255, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.news_upload_to, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Зміст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.page_image_upload_to, verbose_name='Зображення сторінки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок у меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Метаопис'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.page', verbose_name='Батьківська сторінка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва партнера'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='section',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок відображення'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
