# Generated by Django 5.2 on 2025-05-18 16:24

import core.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to=core.models.gallery_upload_to, verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='tags',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.news_upload_to, verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
