# Generated by Django 5.2 on 2025-05-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link_text_en',
            field=models.CharField(default='Дізнатись більше', max_length=255, null=True, verbose_name='Текст посилання'),
        ),
        migrations.AddField(
            model_name='card',
            name='link_text_uk',
            field=models.CharField(default='Дізнатись більше', max_length=255, null=True, verbose_name='Текст посилання'),
        ),
    ]
