# Generated by Django 5.2 on 2025-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_section_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
