# Generated by Django 5.2 on 2025-05-18 20:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.page_image_upload_to, verbose_name='Изображение страницы'),
        ),
    ]
