# Generated by Django 5.2 on 2025-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
