# Generated by Django 5.2 on 2025-05-21 06:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент'),
        ),
    ]
