# Generated by Django 5.2.1 on 2025-06-09 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути у форматі: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('default_address_line1', models.CharField(blank=True, max_length=255, verbose_name='Адреса (рядок 1)')),
                ('default_address_line2', models.CharField(blank=True, max_length=255, verbose_name='Адреса (рядок 2)')),
                ('default_city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('default_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Поштовий індекс')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email повідомлення')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS повідомлення')),
                ('newsletter_subscription', models.BooleanField(default=True, verbose_name='Підписка на розсилку')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Всього замовлень')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всього витрачено')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
