# Generated by Django 5.2 on 2025-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва категорії'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва категорії'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Короткий опис'),
        ),
    ]
