# Generated by Django 5.2 on 2025-06-06 20:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_description_en_category_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Опис'),
        ),
    ]
