# Generated by Django 5.2.1 on 2025-06-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купона')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума'), ('free_shipping', 'Безкоштовна доставка')], max_length=20, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значення знижки')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Залиште порожнім, якщо немає обмежень', max_digits=10, null=True, verbose_name='Мінімальна сума замовлення')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для необмеженого використання', null=True, verbose_name='Ліміт використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Кількість використань')),
                ('valid_from', models.DateTimeField(verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(verbose_name='Дійсний до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Код купона на момент замовлення', max_length=50, verbose_name='Код купона'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума знижки'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon', verbose_name='Використаний купон'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Використано')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='shop.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Використання купона',
                'verbose_name_plural': 'Використання купонів',
                'unique_together': {('coupon', 'order')},
            },
        ),
    ]
