# Generated by Django 5.2.1 on 2025-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Стандартна доставка (2-3 дні) - 50 ₴'), ('express', 'Експрес доставка (наступний день) - 100 ₴'), ('pickup', 'Самовивіз з магазину - безкоштовно'), ('nova_poshta', 'Нова Пошта - 60 ₴')], default='standard', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Оплата при отриманні готівкою'), ('card_on_delivery', 'Оплата при отриманні карткою'), ('online_card', 'Оплата карткою онлайн'), ('bank_transfer', 'Банківський переказ')], default='cash_on_delivery', max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
